version: "3"

networks:
  corp:
    driver: bridge

services:
  myweb-api:
    container_name: myweb-api
    build:
          context: ./backend
          dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000

  next-client:
    container_name: next-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  nginx_proxy:
    container_name: nginx_proxy  
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - myweb-api
      - next-client



  